export { addAcquireJobsCommand } from "./acquireJobs";
export { addArtifactCommand } from "./artifact";
export { addJobClothCommand } from "./jobCloth";
export { addJobJudgeCommand } from "./jobJudge";
export { addJobDbCommand } from "./jobDb";
export { addMakeMaterialsCommands } from "./makeMaterials";
export { addProcessDataCommand } from "./processData";
export { addPreflightCommand } from "./preflight";
export { addRunPipelineCommand } from "./runPipeline";
